name: Deploy to docker

on:
  [push]


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      BASE_REPO: reubinoff/scheduler_listener
      REGISTRY: reubinoff.azurecr.io
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v1
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: 'Log in to the Container registry'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build And Publish Docker
      run: |
        cd listener
        docker-compose build
        docker tag ${{ env.BASE_REPO }}:latest ${{ env.REGISTRY }}/${{ env.BASE_REPO }}:${{ github.sha }}
        docker tag ${{ env.BASE_REPO }}:latest ${{ env.REGISTRY }}/${{ env.BASE_REPO }}:latest
        docker push ${{ env.REGISTRY }}/${{ env.BASE_REPO }}:${{ github.sha }}
        docker push ${{ env.REGISTRY }}/${{ env.BASE_REPO }}:latest
